CREATE TABLE IF NOT EXISTS users (
    user_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    username VARCHAR(20) NOT NULL,
    password VARCHAR(64) NOT NULL,
    role VARCHAR(20) NOT NULL,
    enabled TINYINT DEFAULT NULL
);